/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxGeth.h"
#include "IfxGeth_Eth.h"
#include "IfxStm.h"

#include "ETH_LowLevel.h"
#define STM_INSTANCE (&MODULE_STM0)

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

void delay_ms(uint32 milliseconds);

typedef struct {
    uint8 dest_mac[6];         // Destination MAC (Broadcast)
    uint8 src_mac[6];          // Source MAC
    uint16 vlan_tpid;          // VLAN TPID (0x8100)
    uint16 vlan_tci;           // VLAN TCI (Priority + VLAN ID)
    uint16 ethertype;          // EtherType or Length
    uint8 payload[90];         // Payload (adjust size as needed)
}EthernetFrameWithVLAN;

EthernetFrameWithVLAN test_frame_0 = {
    .dest_mac = {0x02, 0x00, 0x00, 0x00, 0x01, 0x00},
    .src_mac = {0x66, 0x55, 0x44, 0x33, 0x22, 0x11},
    .vlan_tpid = 0x8100,
    .vlan_tci = 0x0006,
    .ethertype = 0x006e,
    .payload = {
        0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55
        }
};
uint8 *raw_bytes_0 = (uint8 *)&test_frame_0;

EthernetFrameWithVLAN test_frame_1 = {
    .dest_mac = {0x02, 0x00, 0x00, 0x00, 0x01, 0x00},
    .src_mac = {0x66, 0x55, 0x44, 0x33, 0x22, 0x11},
    .vlan_tpid = 0x8100,
    .vlan_tci = 0x0006,
    .ethertype = 0x006e,
    .payload = {
        0x11, 0x11,
        0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55
        }
};
uint8 *raw_bytes_1 = (uint8 *)&test_frame_1;


EthernetFrameWithVLAN test_frame_2 = {
    .dest_mac = {0x02, 0x00, 0x00, 0x00, 0x01, 0x00},
    .src_mac = {0x66, 0x55, 0x44, 0x33, 0x22, 0x11},
    .vlan_tpid = 0x8100,
    .vlan_tci = 0x0006,
    .ethertype = 0x006e,
    .payload = {
        0x22, 0x22,
        0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
        0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55
        }
};
uint8 *raw_bytes_2 = (uint8 *)&test_frame_2;

void core0_main(void)
{
    //uint16 i;

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    uint8 numTxQueues = 3;
    uint8 numRxQueues = 1;

    ETH_lowlevel_init_RMII(numTxQueues, numRxQueues);
    //ETH_lowlevel_init_RGMII(numTxQueues, numRxQueues);
    uint8 *payloads[] = { raw_bytes_0, raw_bytes_1, raw_bytes_2 };
    uint16 lengths[] = { sizeof(test_frame_0), sizeof(test_frame_1), sizeof(test_frame_2) };
    while(1)
    {
        delay_ms(5000);
        low_level_output(payloads, lengths, 3);
    }
}

//Timer Frequency is 100 MHz
void delay_ms(uint32 milliseconds)
{
    uint32 ticks = milliseconds * 100000;  // 100,000 ticks per millisecond at 100 MHz
    uint32 start = IfxStm_get(STM_INSTANCE);

    while ((uint32)(IfxStm_get(STM_INSTANCE) - start) < ticks);
}
